False = 0
None = 0

var PizzaShops =

[{'id': 'ysqgdbSrezXgVwER2kQWKA',
  'alias': 'julianas-pizza-brooklyn-5',
  'name': "Juliana's Pizza",
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/7JtwTxhWHf3YS70Ss_CfxA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/julianas-pizza-brooklyn-5?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1942,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.7026153030093,
   'longitude': -73.9934159993549},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '19 Old Fulton St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['19 Old Fulton St', 'Brooklyn, NY 11201']},
  'phone': '+17185966700',
  'display_phone': '(718) 596-6700',
  'distance': 323.20506308227306},
 {'id': 'zj8Lq1T8KIC5zwFief15jg',
  'alias': 'prince-street-pizza-new-york-2',
  'name': 'Prince Street Pizza',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/ZAukOyv530w4KjOHC5YY1w/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/prince-street-pizza-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 2676,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.7229087705545,
   'longitude': -73.9944863319397},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '27 Prince St',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10012',
   'country': 'US',
   'state': 'NY',
   'display_address': ['27 Prince St', 'New York, NY 10012']},
  'phone': '+12129664100',
  'display_phone': '(212) 966-4100',
  'distance': 1941.9638172538225},
 {'id': 'WIhm0W9197f_rRtDziq5qQ',
  'alias': 'lombardis-pizza-new-york-4',
  'name': "Lombardi's Pizza",
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/UZ6V_hobp1KpYDPOHNoCKw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/lombardis-pizza-new-york-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 5828,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7215934960083,
   'longitude': -73.9955956044561},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '32 Spring St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10012',
   'country': 'US',
   'state': 'NY',
   'display_address': ['32 Spring St', 'New York, NY 10012']},
  'phone': '+12129417994',
  'display_phone': '(212) 941-7994',
  'distance': 1798.9959778083735},
 {'id': 'v1DHGRNCH9247WLYoaoA9A',
  'alias': 'l-industrie-pizzeria-brooklyn',
  'name': "L'industrie Pizzeria",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/SRL_RztRRUijgQwt67daGw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/l-industrie-pizzeria-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 407,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 5.0,
  'coordinates': {'latitude': 40.71162, 'longitude': -73.95783},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '254 S 2nd St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11211',
   'country': 'US',
   'state': 'NY',
   'display_address': ['254 S 2nd St', 'Brooklyn, NY 11211']},
  'phone': '+17185990002',
  'display_phone': '(718) 599-0002',
  'distance': 3145.016041338447},
 {'id': '2ggi1luerd3Mf_C82JvCYg',
  'alias': 'grimaldis-pizzeria-brooklyn-4',
  'name': "Grimaldi's Pizzeria",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/TNKqW31PTvtSw6-Lbc1mtA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/grimaldis-pizzeria-brooklyn-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 4464,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 3.5,
  'coordinates': {'latitude': 40.70257, 'longitude': -73.99323},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '1 Front St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1 Front St', 'Brooklyn, NY 11201']},
  'phone': '+17188584300',
  'display_phone': '(718) 858-4300',
  'distance': 327.45636528596714},
 {'id': 'XLks2jXfslR0SzqFlUa6rw',
  'alias': 'best-pizza-shop-queens',
  'name': 'Best Pizza Shop',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/OuC6rPpQA_jb2WXf5S50vw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/best-pizza-shop-queens?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 6,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7589, 'longitude': -73.92601},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '32-20 34th Ave',
   'address2': '',
   'address3': None,
   'city': 'Queens',
   'zip_code': '11106',
   'country': 'US',
   'state': 'NY',
   'display_address': ['32-20 34th Ave', 'Queens, NY 11106']},
  'phone': '',
  'display_phone': '',
  'distance': 8281.481284236419},
 {'id': 'C8j0q4Ma_S5hBGuAI-aaww',
  'alias': 'di-fara-pizza-brooklyn',
  'name': 'Di Fara Pizza',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/4dfe9qpe20P-vi3qFjWd4Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/di-fara-pizza-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 3235,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.625093, 'longitude': -73.961531},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '1424 Ave J',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11230',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1424 Ave J', 'Brooklyn, NY 11230']},
  'phone': '+17182581367',
  'display_phone': '(718) 258-1367',
  'distance': 9352.269072867253},
 {'id': 'oJ_XSPZFpvIt6rvheSQl7A',
  'alias': 'bleecker-street-pizza-new-york',
  'name': 'Bleecker Street Pizza',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/Kyi2tP43S_a6s-zXD38NUQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bleecker-street-pizza-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 2039,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7320627016512,
   'longitude': -74.0036552270137},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '69 7th Ave S',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10014',
   'country': 'US',
   'state': 'NY',
   'display_address': ['69 7th Ave S', 'New York, NY 10014']},
  'phone': '+12129244466',
  'display_phone': '(212) 924-4466',
  'distance': 3072.9540450669765},
 {'id': 'yH6t1JWcwkdWG4CS5KPvow',
  'alias': 'adriennes-pizzabar-new-york',
  'name': "Adrienne's Pizzabar",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/MOG8wpqkeYQxDslq7ospLw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/adriennes-pizzabar-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1528,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'beerbar', 'title': 'Beer Bar'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7043362, 'longitude': -74.0101733},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '54 Stone St',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10004',
   'country': 'US',
   'state': 'NY',
   'display_address': ['54 Stone St', 'New York, NY 10004']},
  'phone': '+12122483838',
  'display_phone': '(212) 248-3838',
  'distance': 1344.2671600758972},
 {'id': 'uc5qQMzs96rzjK27epDCug',
  'alias': 'joes-pizza-new-york-4',
  'name': "Joe's Pizza",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/FhbFkrh_3TrAOZvoWTyOJA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/joes-pizza-new-york-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 2225,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7305599, 'longitude': -74.0021299},
  'transactions': [],
  'price': '$',
  'location': {'address1': '7 Carmine St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10014',
   'country': 'US',
   'state': 'NY',
   'display_address': ['7 Carmine St', 'New York, NY 10014']},
  'phone': '+12123661182',
  'display_phone': '(212) 366-1182',
  'distance': 2873.5532231399425},
 {'id': 'nUpA3sY5b6dynC7aj0eV6A',
  'alias': 'rizzos-fine-pizza-new-york-4',
  'name': "Rizzo's Fine Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/r4OPoXMhNig7p94wdW9yOA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/rizzos-fine-pizza-new-york-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 676,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'},
   {'alias': 'beerbar', 'title': 'Beer Bar'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.720852, 'longitude': -73.984456},
  'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '17 Clinton St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10002',
   'country': 'US',
   'state': 'NY',
   'display_address': ['17 Clinton St', 'New York, NY 10002']},
  'phone': '+16464541262',
  'display_phone': '(646) 454-1262',
  'distance': 1903.2788345091096},
 {'id': 'xxgcU_oFIox_pAmroo9WwA',
  'alias': 'front-street-pizza-brooklyn',
  'name': 'Front Street Pizza',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/3gefrnHNBSjOoa3PKvag9w/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/front-street-pizza-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 295,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.70244, 'longitude': -73.98943},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '80 Front St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['80 Front St', 'Brooklyn, NY 11201']},
  'phone': '+17188753700',
  'display_phone': '(718) 875-3700',
  'distance': 530.2856895611},
 {'id': 'i_rg-OLXQbpRUN7O3MeCeA',
  'alias': 'piz-zetta-brooklyn-2',
  'name': 'Piz-zetta',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/9L4viDwAGx3obgYLnXMA6g/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/piz-zetta-brooklyn-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 242,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.6912834070746,
   'longitude': -73.9906029201042},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '90 Livingston St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['90 Livingston St', 'Brooklyn, NY 11201']},
  'phone': '+17184227878',
  'display_phone': '(718) 422-7878',
  'distance': 1605.1176697811002},
 {'id': 'LF1QAuvpfX7KGQlg2zMg6Q',
  'alias': 'johns-of-bleecker-street-new-york-2',
  'name': "John's of Bleecker Street",
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/ey_5ReYpouWm4SlY2DsaVQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/johns-of-bleecker-street-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1784,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.73158, 'longitude': -74.00332},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '278 Bleecker St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10014',
   'country': 'US',
   'state': 'NY',
   'display_address': ['278 Bleecker St', 'New York, NY 10014']},
  'phone': '+12122431680',
  'display_phone': '(212) 243-1680',
  'distance': 3010.899021476809},
 {'id': 'FhXjAc6nKLf414KxYujUHw',
  'alias': 'robertas-brooklyn-2',
  'name': "Roberta's",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/xRNPKIfF2Gr02zBiBl3dSA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/robertas-brooklyn-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 2632,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.705043534338, 'longitude': -73.93357123374},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '261 Moore St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11206',
   'country': 'US',
   'state': 'NY',
   'display_address': ['261 Moore St', 'Brooklyn, NY 11206']},
  'phone': '+17184171118',
  'display_phone': '(718) 417-1118',
  'distance': 5118.690592147886},
 {'id': 'Q9F2ocrmYuGt1yn3M7MOBw',
  'alias': 'lucali-brooklyn-3',
  'name': 'Lucali',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/zpy57jW_kDZjQdbtIVRx_g/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/lucali-brooklyn-3?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1303,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.6818, 'longitude': -74.00024},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '575 Henry St',
   'address2': None,
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11231',
   'country': 'US',
   'state': 'NY',
   'display_address': ['575 Henry St', 'Brooklyn, NY 11231']},
  'phone': '+17188584086',
  'display_phone': '(718) 858-4086',
  'distance': 2677.3041083372636},
 {'id': 'WG639VkTjmK5dzydd1BBJA',
  'alias': 'rubirosa-new-york-2',
  'name': 'Rubirosa',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/LuSzR8cpVQRofXOT_bMi1A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/rubirosa-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1877,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.72275, 'longitude': -73.99622},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '235 Mulberry St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10012',
   'country': 'US',
   'state': 'NY',
   'display_address': ['235 Mulberry St', 'New York, NY 10012']},
  'phone': '+12129650500',
  'display_phone': '(212) 965-0500',
  'distance': 1931.2683716470422},
 {'id': 'S4uozcDEieoaXxIJ6TsUoQ',
  'alias': 'dellaroccos-brick-oven-pizza-brooklyn',
  'name': "Dellarocco's Brick Oven Pizza",
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/RGsip2vQXryVUbOrXfYBkQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/dellaroccos-brick-oven-pizza-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 233,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'beerbar', 'title': 'Beer Bar'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.6950309, 'longitude': -73.9961252},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '214 Hicks St',
   'address2': None,
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['214 Hicks St', 'Brooklyn, NY 11201']},
  'phone': '+17188581010',
  'display_phone': '(718) 858-1010',
  'distance': 1170.2700329972115},
 {'id': 'ZTsN8TdMXl8SW_AKd_ablw',
  'alias': 'forno-rosso-downtown-brooklyn-2',
  'name': 'Forno Rosso',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/9aKNymymd9out1HSpkLuiA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/forno-rosso-downtown-brooklyn-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 593,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.69446, 'longitude': -73.98316},
  'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '327 Gold St',
   'address2': '',
   'address3': '',
   'city': 'Downtown Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['327 Gold St', 'Downtown Brooklyn, NY 11201']},
  'phone': '+17184513800',
  'display_phone': '(718) 451-3800',
  'distance': 1547.8879856668632},
 {'id': '-CCfu19Uuy_kD2t4ZwsQfA',
  'alias': 'village-square-pizza-new-york-3',
  'name': 'Village Square Pizza',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/lwM4d-BlArnVRhQIIlsxrQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/village-square-pizza-new-york-3?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 43,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.72748, 'longitude': -73.98268},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '147 Ave A',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10009',
   'country': 'US',
   'state': 'NY',
   'display_address': ['147 Ave A', 'New York, NY 10009']},
  'phone': '+19176757709',
  'display_phone': '(917) 675-7709',
  'distance': 2640.263835248777},
 {'id': 'B1XdGwZZ5ee2fBdngj7NUw',
  'alias': 'underground-pizza-new-york',
  'name': 'Underground Pizza',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/gCOE3o5WufGPCaJcin5nNg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/underground-pizza-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 265,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.70499, 'longitude': -74.00961},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '3 Hanover Sq',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10004',
   'country': 'US',
   'state': 'NY',
   'display_address': ['3 Hanover Sq', 'New York, NY 10004']},
  'phone': '+12124254442',
  'display_phone': '(212) 425-4442',
  'distance': 1295.7652741508907},
 {'id': 'eVk4F9ixl89zyUHJ1G2Aiw',
  'alias': 'luzzos-la-pizza-napoletana-new-york-10',
  'name': 'Luzzos La Pizza Napoletana',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/siQq0MnFSCXmAd8rg28EwQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/luzzos-la-pizza-napoletana-new-york-10?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1011,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.730551, 'longitude': -73.9834846},
  'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '211 1st Ave',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10003',
   'country': 'US',
   'state': 'NY',
   'display_address': ['211 1st Ave', 'New York, NY 10003']},
  'phone': '+12124737447',
  'display_phone': '(212) 473-7447',
  'distance': 2936.5316530282876},
 {'id': 'MeQU-nGaQvX12VXYOyzavQ',
  'alias': 'gruppo-new-york-4',
  'name': 'Gruppo',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/O7OTQ9v4Zil2-oykg9NI8Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/gruppo-new-york-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 237,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.72474, 'longitude': -73.98161},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '98 Ave B',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10009',
   'country': 'US',
   'state': 'NY',
   'display_address': ['98 Ave B', 'New York, NY 10009']},
  'phone': '+12129952100',
  'display_phone': '(212) 995-2100',
  'distance': 2395.292393078858},
 {'id': '0UdC0VYX6aAvLiOcpR4MVQ',
  'alias': 'joes-pizza-new-york-7',
  'name': "Joe's Pizza",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/9E2Um0ddicKyoWS-RGIXyg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/joes-pizza-new-york-7?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 765,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.733692, 'longitude': -73.988123},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '150 E 14th St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10003',
   'country': 'US',
   'state': 'NY',
   'display_address': ['150 E 14th St', 'New York, NY 10003']},
  'phone': '+12123889474',
  'display_phone': '(212) 388-9474',
  'distance': 3183.688184836435},
 {'id': 'xrgzB0pvsxeGEIboE6I2gg',
  'alias': 'patsys-pizzeria-brooklyn-2',
  'name': "Patsy's Pizzeria",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/1n5xL5ojLR-_zseirQKaMw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/patsys-pizzeria-brooklyn-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 468,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.6818695, 'longitude': -73.976181},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '450 Dean St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11217',
   'country': 'US',
   'state': 'NY',
   'display_address': ['450 Dean St', 'Brooklyn, NY 11217']},
  'phone': '+17186222268',
  'display_phone': '(718) 622-2268',
  'distance': 3034.9893998767334},
 {'id': 'hGksyTiHBBdrhbiVjXzWVw',
  'alias': 'scarrs-pizza-new-york',
  'name': "Scarr's Pizza",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/k3iXzXNevY7-CuIbE0-FaQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/scarrs-pizza-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 223,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.71534, 'longitude': -73.9914},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '22 Orchard St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10002',
   'country': 'US',
   'state': 'NY',
   'display_address': ['22 Orchard St', 'New York, NY 10002']},
  'phone': '+12123343481',
  'display_phone': '(212) 334-3481',
  'distance': 1125.7843300426755},
 {'id': 'GRXvvB1OKMuW4XDWEaVAlg',
  'alias': 'joes-pizza-brooklyn-8',
  'name': "Joe's Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/zFqYcj13GBxvXQ4oRUGgsw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/joes-pizza-brooklyn-8?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 239,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.71691, 'longitude': -73.958987},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '216 Bedford Ave',
   'address2': '',
   'address3': None,
   'city': 'Brooklyn',
   'zip_code': '11249',
   'country': 'US',
   'state': 'NY',
   'display_address': ['216 Bedford Ave', 'Brooklyn, NY 11249']},
  'phone': '+17183882216',
  'display_phone': '(718) 388-2216',
  'distance': 3239.2966565668607},
 {'id': 'oRdM7n-AfBPBGAlH4Q0Sag',
  'alias': 'my-pie-pizzeria-romana-new-york-2',
  'name': 'My Pie Pizzeria Romana',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/vo36uaolTTa5aREAcddJnw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/my-pie-pizzeria-romana-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 655,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'vegan', 'title': 'Vegan'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.7608512, 'longitude': -73.9694809},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '690 Lexington Ave',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10022',
   'country': 'US',
   'state': 'NY',
   'display_address': ['690 Lexington Ave', 'New York, NY 10022']},
  'phone': '+12123171850',
  'display_phone': '(212) 317-1850',
  'distance': 6505.9564779774955},
 {'id': 'atbANdSznV29GI066I2Ijw',
  'alias': 'champion-pizza-new-york-6',
  'name': 'Champion Pizza',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/SV5N-uxEa1tHUXYLAi43xA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/champion-pizza-new-york-6?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 247,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.7215270996094,
   'longitude': -73.9970855712891},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '17 Cleveland Pl',
   'address2': None,
   'address3': None,
   'city': 'New York',
   'zip_code': '10012',
   'country': 'US',
   'state': 'NY',
   'display_address': ['17 Cleveland Pl', 'New York, NY 10012']},
  'phone': '+12122263777',
  'display_phone': '(212) 226-3777',
  'distance': 1801.4764439408825},
 {'id': 'zmIrZgWhRdyRMrnEs9D3KA',
  'alias': 'la-margarita-pizza-new-york',
  'name': 'La Margarita Pizza',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/7NH6z9iOZETlq8AKFwkcyQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/la-margarita-pizza-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 262,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.7215392420787,
   'longitude': -73.9876275438289},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '168 Ludlow St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10002',
   'country': 'US',
   'state': 'NY',
   'display_address': ['168 Ludlow St', 'New York, NY 10002']},
  'phone': '+19172614983',
  'display_phone': '(917) 261-4983',
  'distance': 1875.7222956933838},
 {'id': '-9NO2IDCJMyNGZMAQ1-VQw',
  'alias': 'ny-pizza-suprema-new-york',
  'name': 'NY Pizza Suprema',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/EqbDXneMuQP6pw6GemVdQA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ny-pizza-suprema-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1763,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7502059936523,
   'longitude': -73.9953231811523},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '413 8th Ave',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10001',
   'country': 'US',
   'state': 'NY',
   'display_address': ['413 8th Ave', 'New York, NY 10001']},
  'phone': '+12125948939',
  'display_phone': '(212) 594-8939',
  'distance': 4977.847939164096},
 {'id': 'vyoA8dxwScuMV_AsTcjQcg',
  'alias': 'l-and-b-spumoni-gardens-brooklyn',
  'name': 'L & B Spumoni Gardens',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/BrTci9PjIwi7V1vkbgkdqg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/l-and-b-spumoni-gardens-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 3398,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.594715, 'longitude': -73.981316},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '2725 86th St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11223',
   'country': 'US',
   'state': 'NY',
   'display_address': ['2725 86th St', 'Brooklyn, NY 11223']},
  'phone': '+17184491230',
  'display_phone': '(718) 449-1230',
  'distance': 12361.163422806636},
 {'id': 'KEEXuHCYhsQJ-zpJhu98bA',
  'alias': 'joes-pizza-new-york-148',
  'name': "Joe's Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/5P5i2QZhxCen55PNdU_TTg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/joes-pizza-new-york-148?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 580,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7545841255557,
   'longitude': -73.9870039190341},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '1435 Broadway',
   'address2': '',
   'address3': None,
   'city': 'New York',
   'zip_code': '10018',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1435 Broadway', 'New York, NY 10018']},
  'phone': '+16465594878',
  'display_phone': '(646) 559-4878',
  'distance': 5498.444221355099},
 {'id': 'kVrTff8uDMSBAaceBwQ7dg',
  'alias': 'saluggis-new-york',
  'name': "Saluggi's",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/P_NI4AhmWBAi4c33PViGMg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/saluggis-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 541,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.720104, 'longitude': -74.003578},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '325 Church St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10013',
   'country': 'US',
   'state': 'NY',
   'display_address': ['325 Church St', 'New York, NY 10013']},
  'phone': '+12122267900',
  'display_phone': '(212) 226-7900',
  'distance': 1808.5885826304711},
 {'id': 'ynQ8NJB7SEAIkuUxopHPvA',
  'alias': 'ignazios-brooklyn',
  'name': "Ignazio's",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/8X6uFKW7BksKs7H8GYsQxA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ignazios-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 436,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 3.0,
  'coordinates': {'latitude': 40.7032251, 'longitude': -73.993782},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '4 Water St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['4 Water St', 'Brooklyn, NY 11201']},
  'phone': '+17185222100',
  'display_phone': '(718) 522-2100',
  'distance': 250.55975929710243},
 {'id': 'Aazjxg21VH2cncWYBAv68Q',
  'alias': 'sottocasa-pizzeria-brooklyn-3',
  'name': 'Sottocasa Pizzeria',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/MbBAMb3kb1VXtF9M5ptazA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/sottocasa-pizzeria-brooklyn-3?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 579,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.688285, 'longitude': -73.989006},
  'transactions': ['delivery'],
  'price': '$$',
  'location': {'address1': '298 Atlantic Ave',
   'address2': None,
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['298 Atlantic Ave', 'Brooklyn, NY 11201']},
  'phone': '+17188528758',
  'display_phone': '(718) 852-8758',
  'distance': 1959.7870021684514},
 {'id': 'YuzOnNDfRKixNJiaVy5Baw',
  'alias': 'robertas-pizza-new-york-2',
  'name': "Roberta's Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/DfRh3ueUr2FONIMGoitPMQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/robertas-pizza-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 178,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7545170712701,
   'longitude': -73.9765970005763},
  'transactions': ['pickup'],
  'price': '$$',
  'location': {'address1': '230 Park Ave',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10169',
   'country': 'US',
   'state': 'NY',
   'display_address': ['230 Park Ave', 'New York, NY 10169']},
  'phone': '+16467470820',
  'display_phone': '(646) 747-0820',
  'distance': 5656.648409458703},
 {'id': 'ZLPYcgEeRllSoeWyr7y4Ig',
  'alias': 'totonnos-brooklyn',
  'name': "Totonno's",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/DPr5z4v_fejTMcYHl31DMw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/totonnos-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 748,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.578805, 'longitude': -73.983811},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '1524 Neptune Ave',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11224',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1524 Neptune Ave', 'Brooklyn, NY 11224']},
  'phone': '+17183728606',
  'display_phone': '(718) 372-8606',
  'distance': 14103.966980872428},
 {'id': '2xQmBB6w-W6lxiex80fA9A',
  'alias': 'luigis-pizzeria-brooklyn-4',
  'name': "Luigi's Pizzeria",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/QgrEW-SMfez8OkMHlgg-Rw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/luigis-pizzeria-brooklyn-4?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 230,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.6897, 'longitude': -73.965369},
  'transactions': ['delivery'],
  'price': '$',
  'location': {'address1': '326 Dekalb Ave',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11205',
   'country': 'US',
   'state': 'NY',
   'display_address': ['326 Dekalb Ave', 'Brooklyn, NY 11205']},
  'phone': '+17187832430',
  'display_phone': '(718) 783-2430',
  'distance': 3001.8318150390764},
 {'id': 'uEKiv6WEPg9dWj10HCur5A',
  'alias': 'table-87-coal-oven-pizza-brooklyn-5',
  'name': 'Table 87 Coal Oven Pizza',
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/P-SRieRAoqpG_o43B8TY8Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/table-87-coal-oven-pizza-brooklyn-5?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 234,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.691219329834, 'longitude': -73.9973449707031},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '87 Atlantic Ave',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['87 Atlantic Ave', 'Brooklyn, NY 11201']},
  'phone': '+17187979300',
  'display_phone': '(718) 797-9300',
  'distance': 1602.5908124268826},
 {'id': 'vfYhEpp0x-DrNjC6GSJjPQ',
  'alias': 'artichoke-basilles-pizza-new-york-2',
  'name': "Artichoke Basille's Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/53JHO_-CRJ_e43JJIuN_Og/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/artichoke-basilles-pizza-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 3787,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7321124557704,
   'longitude': -73.9839056828882},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '321 E 14th St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10003',
   'country': 'US',
   'state': 'NY',
   'display_address': ['321 E 14th St', 'New York, NY 10003']},
  'phone': '+12122282004',
  'display_phone': '(212) 228-2004',
  'distance': 3091.822113723405},
 {'id': '58YvTYsyxNyGixTAZiMHcg',
  'alias': 'williamsburg-pizza-new-york-3',
  'name': 'Williamsburg Pizza',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/bqgarjs0DUMBkSoPDdPtHw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/williamsburg-pizza-new-york-3?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 184,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.71822, 'longitude': -73.99123},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '277 Broome St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10002',
   'country': 'US',
   'state': 'NY',
   'display_address': ['277 Broome St', 'New York, NY 10002']},
  'phone': '+12122264455',
  'display_phone': '(212) 226-4455',
  'distance': 1448.6190383319204},
 {'id': 'BgGz5IdV53bGb4o7opR5zg',
  'alias': 'arturos-new-york',
  'name': "Arturo's",
  'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/eqnPbjFCduD4_v8CIg4EnQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/arturos-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 628,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7273563342024,
   'longitude': -74.0004944801331},
  'transactions': ['restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '106 W Houston St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10012',
   'country': 'US',
   'state': 'NY',
   'display_address': ['106 W Houston St', 'New York, NY 10012']},
  'phone': '+12126773820',
  'display_phone': '(212) 677-3820',
  'distance': 2491.867165709998},
 {'id': 'SpyQHasbnU5YkOR6PI4sNQ',
  'alias': 'margherita-nyc-new-york',
  'name': 'Margherita NYC',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/GOUXE4GPpJ-yDw3CQcSysg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/margherita-nyc-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 270,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7189865112305,
   'longitude': -73.9969329833984},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '197 Grand St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10013',
   'country': 'US',
   'state': 'NY',
   'display_address': ['197 Grand St', 'New York, NY 10013']},
  'phone': '+12122268391',
  'display_phone': '(212) 226-8391',
  'distance': 1531.530627996726},
 {'id': 'C-V8rvmamxMzu7EoQkcFrg',
  'alias': 'kestè-wall-street-new-york-2',
  'name': 'Kestè Wall Street',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/Xtwi7lobwoi3sYSU-nctnA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/kest%C3%A8-wall-street-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 114,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.7089545, 'longitude': -74.0050526},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '77 Fulton St',
   'address2': '',
   'address3': None,
   'city': 'New York',
   'zip_code': '10038',
   'country': 'US',
   'state': 'NY',
   'display_address': ['77 Fulton St', 'New York, NY 10038']},
  'phone': '+12126939030',
  'display_phone': '(212) 693-9030',
  'distance': 953.1574554311165},
 {'id': 'PBsVApRd0dHVjWgiGZgcRQ',
  'alias': 'louie-and-ernies-pizza-bronx-2',
  'name': "Louie & Ernie's Pizza",
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/R-p0ELcXiEwWbkIVUyvRkQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/louie-and-ernies-pizza-bronx-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 249,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.838288, 'longitude': -73.828563},
  'transactions': [],
  'price': '$',
  'location': {'address1': '1300 Crosby Ave',
   'address2': '',
   'address3': '',
   'city': 'Bronx',
   'zip_code': '10461',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1300 Crosby Ave', 'Bronx, NY 10461']},
  'phone': '+17188296230',
  'display_phone': '(718) 829-6230',
  'distance': 20314.878649813818},
 {'id': 'cS2dquz8jSagXqeVKBwSsg',
  'alias': 'fascati-pizza-brooklyn',
  'name': 'Fascati Pizza',
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/_u0bhgV51bK-Xbo_5SQNqw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/fascati-pizza-brooklyn?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 223,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'sandwiches', 'title': 'Sandwiches'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.6985, 'longitude': -73.99273},
  'transactions': [],
  'price': '$',
  'location': {'address1': '80 Henry St',
   'address2': '',
   'address3': '',
   'city': 'Brooklyn',
   'zip_code': '11201',
   'country': 'US',
   'state': 'NY',
   'display_address': ['80 Henry St', 'Brooklyn, NY 11201']},
  'phone': '+17182371278',
  'display_phone': '(718) 237-1278',
  'distance': 783.4896373292174},
 {'id': 'c3D2ckzacnPtdGIM8tb-_w',
  'alias': 'b-side-pizza-and-wine-bar-new-york',
  'name': 'B Side Pizza & Wine Bar',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/m_5goJPoabzTHCyQ2qAVGQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/b-side-pizza-and-wine-bar-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 993,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.5,
  'coordinates': {'latitude': 40.76394, 'longitude': -73.9883399},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '370 W 51st St',
   'address2': None,
   'address3': '',
   'city': 'New York',
   'zip_code': '10019',
   'country': 'US',
   'state': 'NY',
   'display_address': ['370 W 51st St', 'New York, NY 10019']},
  'phone': '+16466797225',
  'display_phone': '(646) 679-7225',
  'distance': 6519.850090048231},
 {'id': '1uOB_tWZwvI0_HakXfu5Jg',
  'alias': 'nicks-pizza-new-york',
  'name': "Nick's Pizza",
  'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/B7wgdiOEVw6yU4RWbAEKyA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/nicks-pizza-new-york?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 497,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.78272, 'longitude': -73.94781},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '1814 2nd Ave',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10128',
   'country': 'US',
   'state': 'NY',
   'display_address': ['1814 2nd Ave', 'New York, NY 10128']},
  'phone': '+12129875700',
  'display_phone': '(212) 987-5700',
  'distance': 9442.562366002065},
 {'id': 'd7Asc4q2ImoPlA_BhfroTQ',
  'alias': 'kesté-pizza-and-vino-new-york-2',
  'name': 'Kesté Pizza & Vino',
  'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/QmCGZCd9KsysWQddAnHTdg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/kest%C3%A9-pizza-and-vino-new-york-2?adjust_creative=EH0taIa-KFi8zcXMtG_RQQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=EH0taIa-KFi8zcXMtG_RQQ',
  'review_count': 1336,
  'categories': [{'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'gluten_free', 'title': 'Gluten-Free'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.0,
  'coordinates': {'latitude': 40.73154, 'longitude': -74.00293},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '271 Bleecker St',
   'address2': '',
   'address3': '',
   'city': 'New York',
   'zip_code': '10014',
   'country': 'US',
   'state': 'NY',
   'display_address': ['271 Bleecker St', 'New York, NY 10014']},
  'phone': '+12122431500',
  'display_phone': '(212) 243-1500',
  'distance': 2991.8818535500936}]
